# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KI on GitHub
email: kangismet@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sebuah catatan Kang Ismet di Github, memuat tentang apa yang disuka baik coding, github, jekyll, vps dll.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "https://kangismet.github.io" # the base hostname & protocol for your site
twitter_username: kangismetdotnet
github_username:  kangismet
disqus_username: kangismetgithub

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"


compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass


images: '/assets/images'
